### PR TITLE
Add pylint

### LINKED ISSUE #2: Add pylint

### PR DESCRIPTION
**Pull request by nicolasvienot**
closes #2 

This is the first draft about adding pylint to this repository.

What has been done :

- Add pylint in the requirements
- Add pylintrc using the one in meilisearch-python **(will be updated according to the digitalocean repo)**
- Add a github action to test with pylint on push and pr
- Format using autopep8
- Fix most of the errors raised by pylint **(will be updated according to the digitalocean repo)**
- Update contributing with development workflow and new file names

About the no-member errors raised by pylint, there is options to put in the pylintrc file :
`generated-members` or `ignored-module`
See https://docs.pylint.org/en/1.6.0/features.html

```************* Module tools.utils
tools/utils.py:21:19: E1101: Instance of 'Resource' has no 'instances' member (no-member)
tools/utils.py:39:15: W0703: Catching too general exception Exception (broad-except)
tools/utils.py:58:15: W0703: Catching too general exception Exception (broad-except)
tools/utils.py:76:15: W0703: Catching too general exception Exception (broad-except)
tools/utils.py:104:15: W0703: Catching too general exception Exception (broad-except)
************* Module tools.build_image
tools/build_image.py:9:0: C0103: Constant name "instance" doesn't conform to '(([A-Z_][A-Z0-9_]*)|(__.*__))$' pattern (invalid-name)
tools/build_image.py:10:0: C0103: Constant name "instance_ip" doesn't conform to '(([A-Z_][A-Z0-9_]*)|(__.*__))$' pattern (invalid-name)
tools/build_image.py:16:15: E1101: Instance of 'Resource' has no 'images' member (no-member)
tools/build_image.py:24:9: E1101: Instance of 'Resource' has no 'instances' member (no-member)
tools/build_image.py:39:15: E1101: Instance of 'Resource' has no 'instances' member (no-member)
tools/build_image.py:55:0: C0103: Constant name "health" doesn't conform to '(([A-Z_][A-Z0-9_]*)|(__.*__))$' pattern (invalid-name)
tools/build_image.py:76:4: C0103: Constant name "ssh_command" doesn't conform to '(([A-Z_][A-Z0-9_]*)|(__.*__))$' pattern (invalid-name)
tools/build_image.py:88:11: E1101: Instance of 'Resource' has no 'instances' member (no-member)
tools/build_image.py:94:26: E1101: Instance of 'Resource' has no 'instances' member (no-member)
tools/build_image.py:100:0: C0103: Constant name "stopped" doesn't conform to '(([A-Z_][A-Z0-9_]*)|(__.*__))$' pattern (invalid-name)
tools/build_image.py:120:25: E1101: Instance of 'Resource' has no 'images' member (no-member)
tools/build_image.py:129:0: C0103: Constant name "image_creation" doesn't conform to '(([A-Z_][A-Z0-9_]*)|(__.*__))$' pattern (invalid-name)
tools/build_image.py:148:0: E1101: Instance of 'Resource' has no 'instances' member (no-member)
************* Module tools.publish_image
tools/publish_image.py:17:15: E1101: Instance of 'Resource' has no 'projects' member (no-member)
tools/publish_image.py:23:0: C0103: Constant name "image_export_operation" doesn't conform to '(([A-Z_][A-Z0-9_]*)|(__.*__))$' pattern (invalid-name)
tools/publish_image.py:45:25: E1101: Instance of 'Resource' has no 'images' member (no-member)

------------------------------------------------------------------
Your code has been rated at 6.45/10 (previous run: 6.45/10, +0.00)```

### CODE REVIEW

**Comment by nicolasvienot** [comment]
@eskombro contributing.md needs to be checked as we need to decide what we put in the setup section or not [see here](https://github.com/meilisearch/meilisearch-digitalocean/pull/148/commits/1dfba134c399263c53d62f1e043bc8197ce8dd9a)

Also, please check last commit as I removed the first initiation to None of the two variables `instance` and `instance_ip` to make pylint happy.

😄

```Your code has been rated at 10.00/10 (previous run: 9.88/10, +0.12)```

**Comment by eskombro** [comment]
LGTM! 🎉 

Regarding the CONTRIBUTING.md instructions, it was done recently and still LGTM, and not the scope of the PR :)

So in my opinion this PR is ready!

Some conflicts must be fixed before merge

**Review by eskombro — COMMENTED** [review]
LGTM! 🎉 

Regarding the CONTRIBUTING.md instructions, it was done recently and still LGTM, and not the scope of the PR :)

So in my opinion this PR is ready!

Some conflicts must be fixed before merge

**Review by eskombro — DISMISSED** [review]

**Review by eskombro — APPROVED** [review]
👌🏽

**Pull request merged**
